apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_ENV: "development"
  APP_DEBUG: "true"
  APP_URL: "http://localhost"
  DB_CONNECTION_STRING: "mongodb://admin:${DB_PASSWORD}@mongodb-client:27017/admin"
  LOG_LEVEL: "verbose"
  CUSTOM_HEADER: "Demo App - Config and Secret Examples"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DB_PASSWORD: "password"
  API_KEY: "8a722908-2dd4-469b-b669-85c37169385f"
  JWT_SECRET: "super-secret-jwt-token-key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-secret-demo
  template:
    metadata:
      labels:
        app: configmap-secret-demo
    spec:
      containers:
      - name: demo-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/config
        - name: secret-volume
          mountPath: /usr/share/nginx/html/secret
          readOnly: true
        - name: index-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_DEBUG
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: API_KEY
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: config-volume
        configMap:
          name: app-config
      - name: secret-volume
        secret:
          secretName: app-secrets
      - name: index-volume
        configMap:
          name: index-html-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>ConfigMap and Secret Demo</title>
      <style>
        body { 
          font-family: Arial, sans-serif; 
          margin: 40px; 
          line-height: 1.6;
          color: #333; 
        }
        h1 { color: #2c3e50; }
        h2 { color: #3498db; margin-top: 30px; }
        .container { 
          max-width: 800px; 
          margin: 0 auto; 
          padding: 20px;
          border: 1px solid #ddd;
          border-radius: 5px;
        }
        .info {
          background-color: #f8f9fa;
          padding: 15px;
          border-radius: 5px;
          margin-bottom: 20px;
        }
        code {
          background-color: #f1f1f1;
          padding: 2px 6px;
          border-radius: 3px;
          font-family: monospace;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>ConfigMap and Secret Demo</h1>
        <p>This page demonstrates how ConfigMaps and Secrets are used in Kubernetes.</p>
        
        <div class="info">
          <h2>Environment Variables from ConfigMap:</h2>
          <ul>
            <li><strong>APP_ENV:</strong> #{APP_ENV}</li>
            <li><strong>APP_DEBUG:</strong> #{APP_DEBUG}</li>
            <li><strong>DB_PASSWORD:</strong> [REDACTED]</li>
          </ul>
        
          <h2>Mounted ConfigMap Files:</h2>
          <p>Check the <code>/config</code> directory in the container.</p>
          
          <h2>Mounted Secret Files:</h2>
          <p>Check the <code>/secret</code> directory in the container.</p>
        </div>
        
        <h2>Try these commands:</h2>
        <code>kubectl exec -it [pod-name] -- sh</code><br>
        <code>ls -la /usr/share/nginx/html/config</code><br>
        <code>cat /usr/share/nginx/html/config/APP_ENV</code><br>
        <code>ls -la /usr/share/nginx/html/secret</code><br>
        <code>cat /usr/share/nginx/html/secret/API_KEY</code>
      </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: configmap-secret-demo
spec:
  selector:
    app: configmap-secret-demo
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: configmap-secret-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /config-demo
        pathType: Prefix
        backend:
          service:
            name: configmap-secret-demo
            port:
              number: 80
