# Custom values for kube-prometheus-stack Helm chart
# See https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml for defaults

# Prometheus configuration
prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    # Enable scraping of Kubernetes API server endpoints
    enableAdminAPI: true
    # Retention configuration
    retention: 10d
    # Pod resources
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        memory: 2Gi
        cpu: 1000m
    # Storage configuration - enable if you want persistent storage
    # storageSpec:
    #   volumeClaimTemplate:
    #     spec:
    #       storageClassName: standard
    #       accessModes: ["ReadWriteOnce"]
    #       resources:
    #         requests:
    #           storage: 10Gi

# Alertmanager configuration
alertmanager:
  service:
    type: ClusterIP
  alertmanagerSpec:
    # Pod resources
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
    # Sample route configuration
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['job', 'alertname', 'severity']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'null'
        routes:
        - match:
            alertname: Watchdog
          receiver: 'null'
      receivers:
      - name: 'null'

# Grafana configuration
grafana:
  service:
    type: ClusterIP
  adminPassword: admin
  sidecar:
    dashboards:
      enabled: true
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  # Additional plugins to install
  plugins:
    - grafana-piechart-panel
    - grafana-clock-panel
  # Additional data sources
  additionalDataSources:
    - name: Loki
      type: loki
      # Replace with your Loki URL if deployed
      url: http://loki-gateway.monitoring.svc.cluster.local
      access: proxy

# Node exporter configuration
nodeExporter:
  enabled: true

# kube-state-metrics configuration
kubeStateMetrics:
  enabled: true

# Prometheus Operator configuration
prometheusOperator:
  createCustomResource: true
